### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jbreitbart** [fast-project/fast-lib#4]
A few things that I found unclear while reading the documentation. All in mqtt_communicator.hpp
- "The async mosquitto loop runs in a seperate thread so internal functions should be threadsafe." We should guarantee if we are threadsafe. Or say we are not threadsafe. :)
- "There is no need to initialize mosquitto before using this class, because this is handled in the constructor and destructor." Sounds like an implementation detail. User should not care.
- \param id is undocumented It is unclear what this actually is.

**Comment by timohl** [comment]
- You are right. Since the class is thread safe the comment should guarantee this.
- Some time ago the user had to call mosqpp::lib_init() before using the communicator. So this was just a note to not do it anymore. Anyway it is obsolete now. ;)
- Yes, this should be documented. It is passed to http://mosquitto.org/api/files/mosquitto-h.html#mosquitto_new. It is important, that it has to be unique. 

I am going to fix those comments soon.
